/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_score_rahasak_utils_OpusEncoder */

#ifndef _Included_com_score_rahasak_utils_OpusEncoder
#define _Included_com_score_rahasak_utils_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_score_rahasak_utils_OpusEncoder
 * Method:    nativeInitEncoder
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_score_rahasak_utils_OpusEncoder_nativeInitEncoder
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_score_rahasak_utils_OpusEncoder
 * Method:    nativeEncodeBytes
 * Signature: ([S[B)I
 */
JNIEXPORT jint JNICALL Java_com_score_rahasak_utils_OpusEncoder_nativeEncodeBytes
  (JNIEnv *, jobject, jshortArray, jbyteArray);

/*
 * Class:     com_score_rahasak_utils_OpusEncoder
 * Method:    nativeReleaseEncoder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_score_rahasak_utils_OpusEncoder_nativeReleaseEncoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
