/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_score_rahasak_utils_OpusDecoder */

#ifndef _Included_com_score_rahasak_utils_OpusDecoder
#define _Included_com_score_rahasak_utils_OpusDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_score_rahasak_utils_OpusDecoder
 * Method:    nativeInitDecoder
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeInitDecoder
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_score_rahasak_utils_OpusDecoder
 * Method:    nativeDecodeBytes
 * Signature: ([B[S)I
 */
JNIEXPORT jint JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeDecodeBytes
  (JNIEnv *, jobject, jbyteArray, jshortArray);

/*
 * Class:     com_score_rahasak_utils_OpusDecoder
 * Method:    nativeReleaseDecoder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_score_rahasak_utils_OpusDecoder_nativeReleaseDecoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

